### ISSUE TITLE
Pitch hangup ALPHA FW

### ISSUE THREAD

**Issue by sandbergfabian** [Normalised/RadioMusic#10]
Hey and thanks for including me in the testing of the new firmware for the RM :D 

Should add that this is my first time using github/trying out new firmware but I've tried to be as thorough as possible.

I spent at few hours trying the new firmware out last night and found I had a few problems, and all of them seem to be related to pitch. I suppose It's best if I submit an issue for each of the problems so lets start of with this one.

I tested the new firmware with 10 banks of RAW-files from the original RM, 2 banks of the same wav-files (one in mono, one in stereo, both 44.100hz so that I could spot differences between stereo and mono with the same material) and the last 3 banks I just used different stereo wav-samples, all in 44.100hz.

The first (and biggest problem) I had was that stereo wav files (and to some extent raw-files) would hangup & loop when the pitch-modulation reached it's highest point (Both via the cv-input and with the start/pitch-potentiometer).  After the hangup occurs none of the pots respond, and the banks can't be changed either. Only a restart of the system would fix it. I could repeat it with almost all stereo-wav files aswell as a few raw-files, but wasn't able to replicate the problem with the mono-wav files.

I've included a link to a recording of what happens when it gets stuck, and also the text-settings on the module.

https://soundcloud.com/mummel-live/pitch-hangup-stereo-rm-alpha/s-9KosE
[SETTINGS.TXT](https://github.com/Normalised/RadioMusic/files/1004945/SETTINGS.TXT)

**Comment by sandbergfabian** [comment]
This one still happens with alpha 5, tried it out with 4 or so different stereo wav and it hangsup on all of them at the top of the pitchrange.

**Comment by Normalised** [comment]
Thanks. I'll look into it.

**Comment by Normalised** [comment]
Just to check this is with 16 bit 44100hz Stereo files?

**Comment by sandbergfabian** [comment]
Most of them are, but just realised a few of the ones I've tried are 24bit 48000hz as well (and they also hangup.)

**Comment by Normalised** [comment]
This is basically fixed ( https://github.com/Normalised/RadioMusic/commit/3170c35002707a3ede9c971a4a937a4d625ee325 ) but i've had to introduce some limits to the range when pitch shifting high bandwidth samples. High bandwidth in this case means anything > 48khz. 

For any files below that limit the range is 26 semitones, for files above the range is 22 semitones.

It's also likely that different types of SD card will have an effect on how reliable pitch shifting upwards is.

Please test with Alpha 6 and let me know how you get on.

**Comment by sandbergfabian** [comment]
I've done some testing now: the stereo-wav files in 44100hz works as they should now, no hangups when reaching the highest pitch. However, the 48000hz stereo-wavs still hangup when reaching the highest pitch. Should I try to make MONO versions of the 48000hz files to see if the problem persists?

For what it's worth, I'm using a sandisk ultra 16gb "10" microsd card.

**Comment by Normalised** [comment]
are they 16 or 24 bit? and if you can test mono that would be great. thanks.

**Comment by sandbergfabian** [comment]
They're 24-bit. I'll get on the mono testing right away.

**Comment by Normalised** [comment]
Ah thanks. Looks like i'll have to limit the pitch range on 24-bit samples a little bit more.
