### ISSUE TITLE
No reset ALPHA FW

### ISSUE THREAD

**Issue by sandbergfabian** [Normalised/RadioMusic#11]
Another problem I have had with the new FW is that reset doesn't work at all when pitchmode is on, either via CV or the restart button.

added settings-text. 
[SETTINGS.TXT](https://github.com/Normalised/RadioMusic/files/1004957/SETTINGS.TXT)

**Comment by Normalised** [comment]
I think this has been fixed, can you check with the latest release please. Alpha 5.

https://github.com/Normalised/RadioMusic/releases

**Comment by sandbergfabian** [comment]
Thanks, didn't realise that there had been new releases. All of my issues occured with Alpha 1 then, I should add.

**Comment by sandbergfabian** [comment]
This also works as it should now.
