### ISSUE TITLE
Distortion/degradation of sound ALPHA FW

### ISSUE THREAD

**Issue by sandbergfabian** [Normalised/RadioMusic#12]
The third problem I had only happened to one of my samples, a mono-wav file. 

I tested the new firmware with 10 banks of RAW-files from the original RM, 2 banks of the same wav-files (one in mono, one in stereo, both 44.100hz so that I could spot differences between stereo and mono with the same material) and the last 3 banks I just used different stereo wav-samples, all in 44.100hz.

There's degradation/distortion of sound (mono wav) if left looping at top-pitch for a little while (10seconds ish). Disapears if sample is switched to another and then back again. Only happens with one of my samples (Mono), but happens every time. Haven't done the "distortion-fix" on the module, might be related? 

Link to problem attached, where can I send you the original file? Dont know if soundcloud is good as it will probably change the original a bit?

https://soundcloud.com/mummel-live/chant-distortion/s-xeeXD
[SETTINGS.TXT](https://github.com/Normalised/RadioMusic/files/1004964/SETTINGS.TXT)

**Comment by Normalised** [comment]
I think this has been fixed, can you check with the latest release please. Alpha 5.

https://github.com/Normalised/RadioMusic/releases

**Comment by sandbergfabian** [comment]
Works fine now :)
