### ISSUE TITLE
Modulation "range"?

### ISSUE THREAD

**Issue by sandbergfabian** [Normalised/RadioMusic#13]
Not sure if this is by design (I think it was the same with the chordorgan, but dont remember about the original RM firmware) but I noticed something with the modulation/pot-range.

Modulation of station and start/pitch only seems to affect the stations and "start-points/pitches" on the "right side" of the pots. (If the start/pitch-pot is set at noon, an lfo modulating the pot would only modulate the "values available between noon and the end of the pot".) Also, an un-attenuated LFO doesn't seem to sweep through the whole range of the start-pot in a smooth way (As it does when you sweep it with your hand). Might be by design? 

So yeah, not sure if it's actually something wrong, just wondering.

**Comment by Normalised** [comment]
Yes, CV inputs only respond to +ve signals.

**Comment by sandbergfabian** [comment]
Thanks.
