### ISSUE TITLE
1v/o tracking consistency

### ISSUE THREAD

**Issue by seanrieger** [Normalised/RadioMusic#14]
Okay, I'm not sure this is a legitimate bug, but I thought I would add as an issue to see if anyone else is seeing the same behavior.  When I am using 1v/o I'm getting some note jumping that reminds me of a quantizer that is having trouble tracking.  I tried it through multiple gates and CV's (KeyStep, PM Midi to CV and Mother 32 Midi to CV) and get some interesting results.  I grabbed a video here (link is not public)  https://youtu.be/D8QZ4tc--LA  if that helps.  Am I just hammering the internal quantizer too fast?

Config - I tried two ways, both below::

crossfade=0
crossfadeTime=25
showMeter=1
meterHide=2000
chanPotImmediate=1
chanCVImmediate=1
startPotImmediate=0
startCVImmediate=0
startCVDivider=2
looping=1
sort=1
pitchMode=1
anyAudioFiles=1

Same results with this config

crossfade=0
crossfadeTime=25
showMeter=1
meterHide=2000
chanPotImmediate=1
chanCVImmediate=1
startPotImmediate=0
startCVImmediate=0
startCVDivider=0
looping=1
sort=1
pitchMode=1
anyAudioFiles=0

**Comment by Normalised** [comment]
Thanks for the video, makes it really clear. I'll do some testing today. 

Looks like the CVs are right on the edges of the quantized values so I might have to shift them half a note along so they land in the middle.

**Comment by Normalised** [comment]
Can you try Alpha 7 please. https://github.com/Normalised/RadioMusic/releases/tag/v2017-alpha.7

I smoothed the inputs when quantising and made it less sensitive around the note boundaries.

I tested with a midi keyboard -> Bitwig -> Expert Sleepers ES-3 and with Alpha 6 I was getting similar results to you. Alpha 7 was very consistent for me when playing from keys.

**Comment by seanrieger** [comment]
Huge improvement. Very consistent on Alpha 7, Nice work!  Thank you.
