### ISSUE TITLE
RM Beta1 freezes when selecting bank 14 with settings.txt from site

### ISSUE THREAD

**Issue by wartaler** [Normalised/RadioMusic#15]
Hi!
I tested the Beta1 now. Overall great job! 

I did run into a little problem when I used the settings file generated on the website http://polyfather.com/radio_music/  :

crossfade=1
crossfadeTime=250
showMeter=1
chanPotImmediate=1
chanCVImmediate=1
startPotImmediate=0
startCVImmediate=0
looping=1
anyAudioFiles=0
pitchMode=0
quantizeRootPot=0
quantizeRootCV=0
startCVDivider=1

When I pushed the reset button to select the bank, my Radiomusic completely froze when it reached bank 14. I repeated this several times, it happens regardless of the content of bank 14, and the only way to get the RM working again is to turn it off, and on..

The problem doesn't occur after I let the RM create the Settings file itself, and then change all the parameters to the same values as above on my computer.. (see below).

Just (and only) by adding anyAudioFiles=0 to the below settings, the problem reoccurred, but with anyAudioFiles=1 everything works fine again. 

crossfade=1
crossfadeTime=250
showMeter=1
meterHide=2000
chanPotImmediate=1
chanCVImmediate=1
startPotImmediate=0
startCVImmediate=0
startCVDivider=1
looping=1
sort=1
pitchMode=0

There is a work-around: leave the parameter out if you're not going to use it. 
Perhaps you can have a look..

Cheers,
Albert

**Comment by Normalised** [comment]
How many files do you have in total across all folders?

**Comment by wartaler** [comment]
I had 163 files in total...  too many, I deleted a 40 and the problem seems to be gone!
and crossfade now actually works, I didn't pay attention
my bad!

**Comment by Normalised** [comment]
Can you try beta 2 and let me know if it still happens.

https://github.com/Normalised/RadioMusic/releases/tag/v2017-beta.2

**Comment by wartaler** [comment]
I tested Beta3, and put all files back on the SD, and it doesn't freeze anymore, 
so: this seems to be fixed!
thanks!
