### ISSUE TITLE
teensy hangs with high pitch modulation and channel change

### ISSUE THREAD

**Issue by eeweegh** [Normalised/RadioMusic#16]
I've seen this repeatably now after installing Radio_Music_2017_Beta_1.hex, with the pitch option enabled: when putting a (say, 2Hz) square wave LFO to the reset input, and another (2Hz, triangle, bipolar 6v) LFO to the pitch input, it seems easy to hang up the module when the pitch CV gets too high (when attenuated, I haven't seen it so far). All you have to do is change the channel knob, and it will freeze after a while: no knobs responsive, audio is stuck in a short loop. Removing the SD card stops the audio, but does no longer reset the module. Power cycle is the only way out.

I am doing this on the original .raw files (the 8+ GB pack Tom mentioned on his site) - don't know why, but drum loops seem to suffer from this more.

FWIW, here's my settings file:
```
crossfade=1
crossfadeTime=50
showMeter=1
chanPotImmediate=1
chanCVImmediate=1
startPotImmediate=1
startCVImmediate=1
looping=1
anyAudioFiles=0
pitchMode=1
quantizeRootPot=1
quantizeRootCV=1
startCVDivider=1
```

Let me know if you need more data - I am not sure which test parameter is really important here.

**Comment by eeweegh** [comment]
extra comment: periodical reset is out of the problem scope - just let a slow (but full amplitude) CV modulate pitch, and change channel as you are on a high pitch.

I've also seen a crash where all four LEDs are lit, and it seems to race at high speed through one of the channels (some song, in my case). No control over the module anymore, but just this whole song playing at breakneck speed. Very funny :-)

**Comment by Normalised** [comment]
ah, so it only happens on the channel change, not if you stay on the same channel?

**Comment by eeweegh** [comment]
indeed, that is what I'm observing (channel = station, just to make sure).

**Comment by Normalised** [comment]
Can you add 'hardSwap=1' to the config file and let me know if it still happens.

**Comment by eeweegh** [comment]
you might be on the right track: added that line, and haven't reproduced it since.

**Comment by Normalised** [comment]
great thanks. so the downside is it turns off crossfading but for now it'll have to be that way. Maybe with some optimisation in the future I can get high pitch and crossfading working.

**Comment by eeweegh** [comment]
no prob - thanks for looking into this.

**Comment by Normalised** [comment]
Beta 2 now makes sure that crossfades are always off in pitch mode.

https://github.com/Normalised/RadioMusic/releases/tag/v2017-beta.2
