### ISSUE TITLE
No sounds from new firmware

### ISSUE THREAD

**Issue by Normalised** [Normalised/RadioMusic#18]
just updated to the latest beta and now there is silence. 

tried several trouble shoots including re-formatting my sd-card. along the way i have been able to check whether the module does function at all or not and what i can tell is that it actually does do something: i inserted the sd-card without any of the settings file and the module did create a new file on its own accord featuring all the new commands as well. so this is great news. 

although, when i start the system up with the card inserted all what happens is that the top left led lights up and stays lit up until i flip the power switch again. when i don't insert a sd-card the top leds are slowly coming on and off one by one, one after another. i suppose it is doing that because it is searching for information which is not there......i'm wondering whether the module recognises my sd-card when it is inserted or not. 

the sd-card is the very same i have used before with the old firmware: 32GB sandisk ultra.

**Comment by 28Eastgate** [comment]
ok...here we go. thank you.

i have the following folders on the sd-card: 16 folder items named "0" up to "15" plus additionally the "settings.txt" file. initially, i did not make any changes to the folder structure from the old firmware but just deleted the individual content.
now, i tried all sorts of *.wav file options, all exported from audacity: mono, 16 or 24 bit, 44100hz or 96000hz sample rate. at one point i also tried unedited field recordings at stereo, 24 bit 96000hz but i was aware that this might not work - it was just to test if there any other signs of life. 
*.wav files are named only "A" or "AA" or "AAA" or "B", just like all the *.raw files before. as this was only a first test run i just included 2 - 3 files in the first three folders. subsequently the remaining folders were empty.
each time, the module did not produce any sound and the top left LED was just continuously on, nothing else.
however, after re-formatting the sd-card and unsuccessfully trying to play back newly exported sound clips i deleted all *.wav files and copied a random collection of my old *.raw files into the first three folders and it now works like a treat.......although, only with *.raw files.

hope that helps.

**Comment by Normalised** [comment]
to use anything apart from .raw and 44/16/mono files you'll need to change the settings.txt file, the easiest way is to use the generator here : 

http://polyfather.com/radio_music/

Select the 'Read any wav files option'

If you want to edit the settings.txt by hand then just add : 

anyAudioFiles=1

If it's still not working after that then let me know.

BUT, I'm curious that you say that you did have 44/16/mono wav files and it didn't work at all.

If you can try a test for me and just put some 44/16/mono wav files in the '0' folder with the standard config (that means WITHOUT anyAudioFiles=1) and let me know if it's still silent.

Thanks.

**Comment by 28Eastgate** [comment]
thank you......issue has been solved now. i can now play 44/16/mono and it works well.
what is strange though is the fact that i am certain that i used only 44/16/mono files in my first attempts as well, after having first used stereo files which, of course, did not work. maybe that's when it all packed up? 
thanks anyway for your swift reply and trouble shooting.
cheers:)

**Comment by Normalised** [comment]
no problem. glad things are working now. there will be some proper instructions soon :)
