### ISSUE TITLE
Random starting point when reset

### ISSUE THREAD

**Issue by wartaler** [Normalised/RadioMusic#2]
Hi!
Now that I managed to compile your firmware version of April 23rd, I was able to test it a little bit further. Apart from the VU metering being restricted to the first LED, I seem to have a problem with the reset function.

I am using a square wave LFO to trigger the reset. With each reset playback seems to start at a different point in the file, near/around the point that I set with the Start knob. This isn't the case with the 2.0b3 'crossfade' beta, where the starting point is repeated pretty accurately.

I was wondering if you get the same behavior with your build, or if this could (again) be due to wrong versions of libraries that I am using to compile it.

To compile the firmware, I used a fresh install of Arduino IDE 1.8.1 and Teensyduino 1.36. 
I didn't update or change any of the libraries, Arduino IDE did notify me that there were some updates available for some of the libraries, but I ignored that.

Thanks in advance!
Albert

**Comment by Normalised** [comment]
Can you paste the config file on the SD card here please.

**Comment by wartaler** [comment]
Yes sure, I first deleted the Settings prior, and let the RM write them by inserting the SD card just after installation of the firmware, so it's just the defaults I guess

mute=0
declick=25
showMeter=1
meterHide=2000
chanPotImmediate=1
chanCVImmediate=1
startPotImmediate=0
startCVImmediate=0
startCVDivider=2
looping=0
sort=1

The only difference is that I normally have looping on, and declick=100
Is there anything I have to add / change with the new firmware?

Cheers,
Albert

**Comment by Normalised** [comment]
Thanks. How long are the audio files that you are using?

**Comment by wartaler** [comment]
The one that works fine is the very short VINYL sample,
I tested different (raw) files varying between 3 and 30 minutes minutes long, all gave audible variation in starting point with above settings.

**Comment by wartaler** [comment]
Same results with .wav files. I think the longer the file is, the greater the variation in starting point.
With the 2.0b3 'crossfade' beta firmware I never noticed this with the same settings and files.

**Comment by Normalised** [comment]
I'll fix it :)

The main difference between the newer version and older is I use a higher resolution for the Pot / CV inputs (13 bit vs 10 bit or 8192 vs 1024) which often means that you get a much noisier input signal.

Today's commit might fix that but i'll do some testing with long files. So far i've only tested with short audio files so i've not noticed the issue.

**Comment by wartaler** [comment]
Ok, or I could increase startCVDivider, but then the net result would be the same (?)

**Comment by Normalised** [comment]
Actually I meant to make the CV divider backwards compatible but I forgot to add the multiply in. I've just added it now. I also added some changes that should make the start control more reliable. Basically made the input smoothing the same as before and increased the change threshold.

**Comment by wartaler** [comment]
Thanks a lot! Tested it and it works!!
