### ISSUE TITLE
Looping: files don't 'continue playing in the background'

### ISSUE THREAD

**Issue by wartaler** [Normalised/RadioMusic#4]
Hi, sorry to bother you again :)
I just compiled the version with 'fix glitch when changing samples' 
In previous version, the looping didn't work (despite setting looping=1)
With the current version, looping does work but :
-the reset light doesn't blink when the starting point is reached (minor thing)
-the loop is sometimes reset by turning the station knob; if I listen to one station for a short while, then go back to the other, that one seems to have been reset - while both files are quite long and the end not reached

setup:
2 files in one bank, both about 30 minutes 

crossfade=1
crossfadeTime=100
showMeter=1
meterHide=2000
chanPotImmediate=1
chanCVImmediate=1
startPotImmediate=0
startCVImmediate=0
startCVDivider=2
looping=1
sort=1
pitchMode=0

**Comment by Normalised** [comment]
No bother. All bug reports are really helpful. :)

I've just made some commits that should make the 'play in background' behave more like the old firmwares.

https://github.com/Normalised/RadioMusic/commit/a0248d772bec1479a19b7041d7c86d1cf20878f3

**Comment by wartaler** [comment]
Thanks, I will test this tomorrow night!

**Comment by Normalised** [comment]
Alpha 4 should be fine for this so use at least that version for testing.

https://github.com/Normalised/RadioMusic/releases

**Comment by wartaler** [comment]
Yes, works !
excellent!
wow!
