### ISSUE TITLE
No reset on button or gate/trig

### ISSUE THREAD

**Issue by erstlaub** [Normalised/RadioMusic#5]
Installed the latest build (alpha 2). Pitch manipulation, bank and station select all work as intended but neither the reset button nor a 5v gate/trig applied to reset in cause the restart from beginning of file expected as per the notes.

I added pitchMode=1 to the config but this did not change the behaviour.

I'm playing back the standard RM formatted raw files, have yet to test with wav.

Cheers

**Comment by Normalised** [comment]
Can you paste the full config please just for completeness. thanks

**Comment by erstlaub** [comment]
MUTE=1
DECLICK=15
ShowMeter=1
meterHIDE=2000
ChanPotImmediate=1
ChanCVImmediate=1
StartPotImmediate=0
StartCVImmediate=0
StartCVDivider=2
Looping=1
pitchMode=1
anyAudioFiles=1

I just noticed that the chordorg.txt was also sitting in the root of the SD card, have deleted it and retested just incase but no change.

**Comment by Normalised** [comment]
Thanks. Fixed in Alpha 3.

https://github.com/Normalised/RadioMusic/releases/tag/v2017-alpha.3
