### ISSUE TITLE
pitchMode=1

### ISSUE THREAD

**Issue by Northpaw27** [Normalised/RadioMusic#7]
Adding pitchMode=1 to the config seems to make my Radio Music just show the first LED with no sound output. Anyone else found this?

**Comment by Normalised** [comment]
Can you try with Alpha 4 from the releases page please.

https://github.com/Normalised/RadioMusic/releases

If its still occurring then paste the full config file and let me know the contents of the SD card.

**Comment by Northpaw27** [comment]
No change with Alpha 4. SD card is full of RAW files, 16 folders.

MUTE=0
DECLICK=15
ShowMeter=1
meterHIDE=2000
ChanPotImmediate=1
ChanCVImmediate=1
StartPotImmediate=0
StartCVImmediate=0
StartCVDivider=2
Looping=1
pitchMode=1

**Comment by wartaler** [comment]
I had the same, the RM didn't like it when I added the line pitchMode=1 to the existing Settings file. 
The trick for me was to delete the Settings file and let the module with the new firmware write a new one, then edit it to engage pitch mode.

**Comment by Normalised** [comment]
ah. that helps. I probably missed something when I was updating the settings.

@Northpaw27 does it work with the new firmware but without the pitchMode=1 in the config?

**Comment by Northpaw27** [comment]
Thanks Wartaler, thats seems to have worked! 
looks like "sort=1 pitchMode=0” were added in the fresh config file

**Comment by Normalised** [comment]
Fixed by https://github.com/Normalised/RadioMusic/commit/66ebc02de87082244937db2df5b0c85fea6ef05f

Available in alpha 5

https://github.com/Normalised/RadioMusic/releases/tag/v2017-alpha.5
