### ISSUE TITLE
48 file limit in folder 15?

### ISSUE THREAD

**Issue by seanrieger** [Normalised/RadioMusic#9]
First of all, really nice job! So far so good. Here's the only thing I've figured out: 

First boot with 32GB disk in that was functioning on old firmware and solid red light on first LED with no sound, no ability to switch folders etc...  Switched cards from my other Radio Music module and everything worked.  Compared settings, between cards and no difference. Tracked it down to having 53 raw files in folder 15.  I removed one at a time until I hit 48 and then everything started working. 49, and no joy.  I added 54 files to folder 13 and no issues, it appears to be only folder 15. Can anyone else confirm?  I don't believe it's total number of files either as I added more files from another card to lower folders and everything worked. 

crossfade=0
crossfadeTime=25
showMeter=1
meterHide=2000
chanPotImmediate=1
chanCVImmediate=1
startPotImmediate=0
startCVImmediate=0
startCVDivider=2
looping=0
sort=1
pitchMode=1

**Comment by Normalised** [comment]
Thanks, i'll get onto this one. good detective work :)

**Comment by Normalised** [comment]
Fixed by 

https://github.com/Normalised/RadioMusic/commit/a8c2d649b6e6102055594ea8c5d4d3e1a3ce7165

Available in Alpha 5

https://github.com/Normalised/RadioMusic/releases/tag/v2017-alpha.5
